require:
  - rubocop-rails
  - rubocop-rspec
  - money

AllCops:
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false
  Exclude:
    - bin/**
    - db/migrate/**
    - db/schema.rb

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/VariableName:
  Enabled: false

Money/MissingCurrency:
  Enabled: true

Money/ZeroMoney:
  Enabled: true